In [1]:
import pandas as pd

In [2]:
#Read CSV file 
oxford_clean = pd.read_csv("Resources/oxford_latest.csv", low_memory=False)
oxford_clean.head()

,CountryName,CountryCode,RegionName,RegionCode,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Aruba,ABW,NaN,NaN,20200101,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Aruba,ABW,NaN,NaN,20200102,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Aruba,ABW,NaN,NaN,20200103,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Aruba,ABW,NaN,NaN,20200104,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Aruba,ABW,NaN,NaN,20200105,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
oxford_clean = oxford_clean[["CountryName","Date", "C1_School closing", "C2_Workplace closing", \
                             "C6_Stay at home requirements", "H6_Facial Coverings", "ConfirmedCases", "ConfirmedDeaths"]]
oxford_clean.head()

,CountryName,Date,C1_School closing,C2_Workplace closing,C6_Stay at home requirements,H6_Facial Coverings,ConfirmedCases,ConfirmedDeaths
0,Aruba,20200101,0.0,0.0,0.0,0.0,NaN,NaN
1,Aruba,20200102,0.0,0.0,0.0,0.0,NaN,NaN
2,Aruba,20200103,0.0,0.0,0.0,0.0,NaN,NaN
3,Aruba,20200104,0.0,0.0,0.0,0.0,NaN,NaN
4,Aruba,20200105,0.0,0.0,0.0,0.0,NaN,NaN