In [4]:
# Import Dependencies 
import pandas as pd
import numpy as np

In [5]:
#Read CSV file
oxford_data = pd.read_csv("Resources/oxford_latest.csv", low_memory=False)
oxford_data.head(10)

,CountryName,CountryCode,RegionName,RegionCode,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,Aruba,ABW,NaN,NaN,20200101,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Aruba,ABW,NaN,NaN,20200102,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Aruba,ABW,NaN,NaN,20200103,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Aruba,ABW,NaN,NaN,20200104,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Aruba,ABW,NaN,NaN,20200105,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Aruba,ABW,NaN,NaN,20200106,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Aruba,ABW,NaN,NaN,20200107,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,Aruba,ABW,NaN,NaN,20200108,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,Aruba,ABW,NaN,NaN,20200109,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,Aruba,ABW,NaN,NaN,20200110,0.0,NaN,0.0,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# Create new dataframe with `CountryName` as index
oxford_data = oxford_data.set_index("CountryName")
oxford_data

,CountryCode,RegionName,RegionCode,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,C3_Flag,...,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
CountryName,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,NaN,NaN,20200101,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
Aruba,ABW,NaN,NaN,20200102,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
Aruba,ABW,NaN,NaN,20200103,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
Aruba,ABW,NaN,NaN,20200104,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
Aruba,ABW,NaN,NaN,20200105,0.0,NaN,0.0,NaN,0.0,NaN,...,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zimbabwe,ZWE,NaN,NaN,20201024,2.0,1.0,1.0,1.0,2.0,1.0,...,71.3,71.3,77.38,77.38,57.14,57.14,62.50,62.50,25.0,25.0
Zimbabwe,ZWE,NaN,NaN,20201025,2.0,1.0,1.0,1.0,2.0,1.0,...,71.3,71.3,77.38,77.38,57.14,57.14,62.50,62.50,25.0,25.0
Zimbabwe,ZWE,NaN,NaN,20201026,2.0,1.0,1.0,1.0,2.0,1.0,...,71.3,71.3,77.38,77.38,60.71,60.71,66.67,66.67,25.0,25.0
Zimbabwe,ZWE,NaN,NaN,20201027,2.0,1.0,1.0,1.0,2.0,1.0,...,71.3,71.3,77.38,77.38,60.71,60.71,66.67,66.67,25.0,25.0
Zimbabwe,ZWE,NaN,NaN,20201028,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,71.3,NaN,77.38,NaN,60.71,NaN,66.67,NaN,25.0

In [9]:
# Create new dataframe with the 12 countries of interest\n",
countries = oxford_data.loc[["Brazil", "Canada", "China", "Germany", "Italy", "Japan", \
                             "New Zealand", "South Korea", "Sweden", "United Kingdom", "United States"]]

oxford_df = pd.DataFrame(countries, columns = ["Date", "C1_School closing", "C2_Workplace closing", "C6_Stay at home requirements", \
                                               "H6_Facial Coverings", "ConfirmedCases", "ConfirmedDeaths"])
oxford_df.reset_index()

,CountryName,Date,C1_School closing,C2_Workplace closing,C6_Stay at home requirements,H6_Facial Coverings,ConfirmedCases,ConfirmedDeaths
0,Brazil,20200101,0.0,0.0,0.0,0.0,0.0,0.0
1,Brazil,20200102,0.0,0.0,0.0,0.0,0.0,0.0
2,Brazil,20200103,0.0,0.0,0.0,0.0,0.0,0.0
3,Brazil,20200104,0.0,0.0,0.0,0.0,0.0,0.0
4,Brazil,20200105,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
20229,United States,20201024,NaN,NaN,NaN,NaN,10805.0,68.0
20230,United States,20201025,NaN,NaN,NaN,NaN,11041.0,68.0
20231,United States,20201026,NaN,NaN,NaN,NaN,11477.0,77.0
20232,United States,20201027,NaN,NaN,NaN,NaN,11806.0,77.0
20233,United States,20201028,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#Save new DataFrame to a csv file
oxford_df.to_csv("output_data/oxford_clean.csv", index=False)